// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfqb8wpMqjRc3AZZgZRKai5BNSrp58Do',
    appId: '1:114514307377:web:ae106e7cd86704cae72810',
    messagingSenderId: '114514307377',
    projectId: 'printellect-interview',
    authDomain: 'printellect-interview.firebaseapp.com',
    storageBucket: 'printellect-interview.firebasestorage.app',
    measurementId: 'G-N43K0JPSKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvXWIu25pw9lwcWQE76xDHQthM7iN1FE',
    appId: '1:114514307377:android:4285cf77f92b0793e72810',
    messagingSenderId: '114514307377',
    projectId: 'printellect-interview',
    storageBucket: 'printellect-interview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHA7wTFDfOZVjykm3cc5Qe6XvfbToKArk',
    appId: '1:114514307377:ios:0dc59237a038fa87e72810',
    messagingSenderId: '114514307377',
    projectId: 'printellect-interview',
    storageBucket: 'printellect-interview.firebasestorage.app',
    iosBundleId: 'com.example.printellectTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHA7wTFDfOZVjykm3cc5Qe6XvfbToKArk',
    appId: '1:114514307377:ios:0dc59237a038fa87e72810',
    messagingSenderId: '114514307377',
    projectId: 'printellect-interview',
    storageBucket: 'printellect-interview.firebasestorage.app',
    iosBundleId: 'com.example.printellectTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRfqb8wpMqjRc3AZZgZRKai5BNSrp58Do',
    appId: '1:114514307377:web:719bc540114bfe64e72810',
    messagingSenderId: '114514307377',
    projectId: 'printellect-interview',
    authDomain: 'printellect-interview.firebaseapp.com',
    storageBucket: 'printellect-interview.firebasestorage.app',
    measurementId: 'G-DW1WXB249S',
  );
}
